services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '3080:8080'
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  mongo-data:
  postgres-data:
