services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${db}
      - MONGO_INITDB_ROOT_USERNAME=${db_user}
      - MONGO_INITDB_ROOT_PASSWORD=${db_pw}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3080:8080"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=${db}
      - DB_USERNAME=${db_user}
      - DB_PASSWORD=${db_pw}
      - JWT_SECRET=your-very-long-secure-secret-string-32+chars
      - REGISTRATION_ENABLED=true
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -s http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"' || exit 1"
      ]
      interval: 10s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
      
volumes:
  mongo-data:
  postgres-data:
