apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/noahrau/todoapp-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_BACKEND_URL
              value: http://backend.default.svc.cluster.local:8080/api/v1