apiVersion: v1
kind: Secret
metadata:
  name: mongodb-app-creds
  namespace: default
type: Opaque
data:
  mongodb-username: bW9uZ291c2Vy
  mongodb-password: bW9uZ29wYXNzd29yZA==
  mongodb-database: dG9kb2FwcA==