
apiVersion: v1
kind: Service
metadata:
  name: background-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: background-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30082
