apiVersion: v1
kind: Service
metadata:
  name: background-service
spec:
  type: NodePort
  selector:
    app: background-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30082
