name: Integration Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration Tests (with Testcontainers)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run integration tests
        working-directory: ./backend
        env:
          DB_NAME: todoapp_test
          DB_USERNAME: root
          DB_PASSWORD: example
          REGISTRATION_ENABLED: true
          JWT_SECRET: "integration-test-secret-which-is-32-byte"
        run: mvn verify -Pintegration-test
