name: linting

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint (ktlint)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.2.1/ktlint && chmod +x ktlint

      - name: Run ktlint
        id: ktlint
        run: ./ktlint "**/*.kt" || echo "LINT_FAILED=true" >> $GITHUB_ENV

      - name: Comment PR on Lint Failure
        if: env.LINT_FAILED == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "🚨 **Lint checks failed!** Please run `ktlint -F '**/*.kt'` locally and commit fixes."

      - name: Fail on lint error
        if: env.LINT_FAILED == 'true'
        run: exit 1